puts "Through gem"
puts "Through gem"
puts "Through gem"
puts "Through gem"
puts "Through gem"
puts "Through gem"
puts "Through gem"
puts "Through gem"
puts "Through gem"
puts "Through gem"
puts "Through gem"
puts "Through gem"
puts "Through gem"
puts "Through gem"

